version: '3.8'

services:
  app:
    container_name: funtech-front
    image: node:16-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=https://funtech-back.azurewebsites.net/
